apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: espsrccanfar-s
  namespace: skaha-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store-canfar
    kind: SecretStore
  target:
    name: espsrccanfar-s
    creationPolicy: Owner
  data:
    - secretKey: CLIENT-ID
      remoteRef:
        key: app/data/espsrccanfar
        property: client-id
    - secretKey: CLIENT-SECRET
      remoteRef:
        key: app/data/espsrccanfar
        property: client-secret
    - secretKey: TOKEN
      remoteRef:
        key: app/data/espsrccanfar
        property: token