apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrccanfar-base
  namespace: skaha-system
  #namespace: espsrccanfar
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: science-platform
        #namespace: flux-system
        #namespace: espsrccanfar
        namespace: skaha-system
      install:
        createNamespace: true
      version: 0.3.3
#  valuesFrom:
#    - kind: Secret
#      name: espsrccanfar-s
#      name: espsrccanfar-s
#      valuesKey: TOKEN
#      targetPath: proxy.secretToken
#      optional: false
#    - kind: Secret
#      name: espsrccanfar-s
#      valuesKey: CLIENT-ID
#      targetPath: hub.config.GenericOAuthenticator.client_id
#      optional: false
#    - kind: Secret
#      name: espsrccanfar-s
#      valuesKey: CLIENT-SECRET
#      targetPath: hub.config.GenericOAuthenticator.client_secret
#      optional: false
#    - kind: ConfigMap
#      name: canfar-values