apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrccanfar-posixmapper
  namespace: espsrccanfar
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: posixmapper
      sourceRef:
        kind: HelmRepository
        name: science-platform
        #namespace: flux-system
        namespace: espsrccanfar
      version: 0.1.9
  valuesFrom:
    - kind: ConfigMap
      name: espsrccanfar-values