apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrccanfar-posixmapper
  #namespace: espsrccanfar
  namespace: skaha-system
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: posixmapper
      sourceRef:
        kind: HelmRepository
        name: science-platform
        #namespace: flux-system
        #namespace: espsrccanfar
        namespace: skaha-system
      version: 0.4.0
  valuesFrom:
    - kind: ConfigMap
      name: posixmapper-values