apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrccanfar-science-platform
  #namespace: espsrccanfar
  namespace: skaha-system
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: skaha
      sourceRef:
        kind: HelmRepository
        name: science-platform
        #namespace: espsrccanfar
        namespace: skaha-system
      #version: 0.4.6
  valuesFrom:
    - kind: ConfigMap
      name: skaha-values