apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# use this order
resources:
  - helmrepository.yaml
  - ServiceAccount.yaml
  - ClusterRoleBinding.yaml
  - SecretStore.yaml
  - ExternalSecret.yaml
  - pv.yaml
  - pvc.yaml
  - values.yaml
  - helmrelease-base.yaml
  - helmrelease-posixmapper.yaml
  - helmrelease-science-platform.yaml
namespace: skaha-system