apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# use this order
resources:
  - namespaces.yaml
  - kustomization-namespaces.yaml
  - helmrepository.yaml
  - ServiceAccount.yaml
  - ClusterRoleBinding.yaml
  - SecretStore.yaml
  - ExternalSecret.yaml
  - pv.yaml
  - pvc.yaml
  - values-posixmapper.yaml
  - values-skaha.yaml
  - values-scienceportal.yaml
  - values-cavern.yaml
  - values-storageui.yaml
  - helmrelease-base.yaml
  - helmrelease-posixmapper.yaml
  - helmrelease-skaha.yaml
  - helmrelease-science-portal.yaml
  - helmrelease-cavern.yaml
  - helmrelease-storageui.yaml
#namespace: skaha-system