apiVersion: v1
kind: ConfigMap
metadata:
  name: storageui-values
  namespace: skaha-system
data:
  values.yaml: |
    deployment:
      hostname: dev.canfar.espsrc.iaa.csic.es
      storageUI:
        image: images.opencadc.org/client/storage-ui:1.1.8
        imagePullPolicy: Always

        # Resources provided to the Skaha service.
        resources:
          requests:
            memory: "500M"
            cpu: "500m"
          limits:
            memory: "500M"
            cpu: "500m"

        # Dictionary of all VOSpace APIs (Services) available that will be visible on the UI.
        # Format is:
        backend:
          defaultService: manucavern
          services:
            manucavern:
              resourceID: "ivo://espsrc.iaa.csic.es/cavern"
              nodeURIPrefix: "vos://espsrc.iaa.csic.es~cavern"
              userHomeDir: "/home"
              features:
                batchDownload: false
                batchUpload: false
                externalLinks: false
                paging: false

        # ID (URI) of the GMS Service.
        gmsID: ivo://skao.int/gms

        oidc:
          # Location of the OpenID Provider (OIdP), and where users will login
          uri: https://ska-iam.stfc.ac.uk/

          # The Client ID as listed on the OIdP.  Create one at the uri above.
          clientID:  d8f92ce0-4860-4992-8a08-10619f61fae4

          # The Client Secret, which should be generated by the OIdP.
          clientSecret: c_tak_NudZoyy4mspQ58NdZLTuTJg55u0k3E3n-c4YE1IrSEqDoKZSmGaRD0ngYhcuNAcatZIRwH1lWgdOKZ7A

          # Where the OIdP should send the User after successful authentication.  This is also known as the redirect_uri in OpenID.  This URI NEEDS
          redirectURI: https://dev.canfar.espsrc.iaa.csic.es/storage/oidc-callback

          # Where to redirect to after the redirectURI callback has completed.  This will almost always be the URL to the /science-portal main page (https://example.com/science-portal).
          callbackURI: https://dev.canfar.espsrc.iaa.csic.es/storage/list

          # The standard OpenID scopes for token requests.  This is required, and if using the SKAO IAM, can be left as-is.
          scope: "openid profile offline_access"
        # OIDC (IAM) server configuration.  These are required
        # oidc:
          # Location of the OpenID Provider (OIdP)
          # uri: https://ska-iam.stfc.ac.uk/
          # The Client ID as listed on the OIdP.
          # clientID:
          # The Client Secret, which should be generated by the OIdP.
          # clientSecret:
          # Where the OIdP should send the User after successful authentication (redirect_uri)
          # redirectURI:
          # Where to redirect to after the redirectURI callback has completed.  This will usually be the URL to the /storage/list main page.
          # callbackURI:
          # The standard OpenID scopes for token requests.  This is required.
          # scope: "openid profile offline_access"

        registryURL: https://spsrc27.iaa.csic.es/reg

        # The IdentityManager class handling authentication.  This should generally be left alone
        #identityManagerClass: org.opencadc.auth.StandardIdentityManager

        # Optionally mount a custom CA certificate
        # extraVolumeMounts:
        # - mountPath: "/config/cacerts"
        #   name: cacert-volume

        # Create the CA certificate volume to be mounted in extraVolumeMounts
        # extraVolumes:
        # - name: cacert-volume
        #   secret:
        #     defaultMode: 420
        #     secretName: storage-ui-cacert-secret

        # Default theme is the SRC one.
        themeName: src

    # secrets:
      # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
      # storage-ui-cacert-secret:
      #   ca.crt: <base64 encoded ca crt>

    # For the token caching
    redis:
      architecture: 'standalone'
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
