apiVersion: v1
kind: ConfigMap
metadata:
  name: science-portal-values
  #namespace: espsrccanfar
  namespace: skaha-system
data:
  values.yaml: |
    # Tell Kubernetes to spin up multiple instances.  Defaults to 1.
    replicaCount: 1

    # It's best to keep these set as such, unless you're willing to change these in several places.
    skaha:
      namespace: skaha-system
    deployment:
      hostname: dev.canfar.espsrc.iaa.csic.es # Change this!
      sciencePortal:
        image: images.opencadc.org/platform/science-portal:0.5.3
        imagePullPolicy: Always
        themeName: "src"
        oidcURI: https://ska-iam.stfc.ac.uk/

        resources:
          requests:
            memory: "500M"
            cpu: "500m"
          limits:
            memory: "500M"
            cpu: "500m"
          # The Resource ID of the Service that contains the URL of the Skaha service in the IVOA Registry
        skahaResourceID: ivo://dev.espsrc.iaa.csic.es/skaha # ORIGINAL example.org, overlay OVERRIDE
        
        gmsID: ivo://skao.int/gms

        # OIDC (IAM) server configuration.  These are required
        oidc:
          # Location of the OpenID Provider (OIdP), and where users will login
          uri: https://ska-iam.stfc.ac.uk/
          #uri: http://spsrc25.iaa.csic.es:18024/

          # The Client ID as listed on the OIdP.  Create one at the uri above.
          clientID:  d8f92ce0-4860-4992-8a08-10619f61fae4
          #clientID: 87f3b754-d751-4f4b-a2ee-4b436757361c
          # The Client Secret, which should be generated by the OIdP.
          clientSecret: c_tak_NudZoyy4mspQ58NdZLTuTJg55u0k3E3n-c4YE1IrSEqDoKZSmGaRD0ngYhcuNAcatZIRwH1lWgdOKZ7A
          #clientSecret: ALN-67opkQNhLUHtlrFfy6PlI6X_5iMivoBU3iFE05I34-VgzQA31veY5u8FREvtVNfOAIuPeAZVasWQDEu4oUA
          # Where the OIdP should send the User after successful authentication.  This is also known as the redirect_uri in OpenID.  This URI NEEDS
          redirectURI: https://dev.canfar.espsrc.iaa.csic.es/science-portal/oidc-callback

          # Where to redirect to after the redirectURI callback has completed.  This will almost always be the URL to the /science-portal main page (https://example.com/science-portal).
          callbackURI: https://dev.canfar.espsrc.iaa.csic.es/science-portal/

          # The standard OpenID scopes for token requests.  This is required, and if using the SKAO IAM, can be left as-is.
          scope: "openid profile offline_access"

        # Optionally mount a custom CA certificate
        # extraVolumeMounts:
        # - mountPath: "/config/cacerts"
        #   name: cacert-volume

        # Create theCA certificate volume to be mounted in extraVolumeMounts
        # extraVolumes:
        # - name: cacert-volume
        #   secret:
        #     defaultMode: 420
        #     secretName: science-portal-cacert-secret

        #gmsID: http://spsrc25.iaa.csic.es:18023
        registryURL: https://spsrc27.iaa.csic.es/reg

        identityManagerClass: org.opencadc.auth.StandardIdentityManager

        # The logo in the top left.  No link associated, just the image.  This can be relative, or absolute.
        # Default is the SRCNet Logo.
        #logoURL: /science-portal/images/SRCNetLogo.png
        themeName: src

    # secrets:
      # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
      # science-portal-cacert-secret:
        # ca.crt: <base64 encoded ca.crt blob>
    # For the token caching
    redis:
      architecture: 'standalone'
      auth:
        enabled: false
      master:
        persistence:
          enabled: false

