apiVersion: v1
kind: ConfigMap
metadata:
  name: posixmapper-values
  #namespace: espsrccanfar
  namespace: skaha-system
data:
  values.yaml: |
    replicaCount: 1

    # It's best to keep these set as such, unless you're willing to change these in several places.
    skaha:
      namespace: skaha-system

    # POSIX Mapper web service deployment
    deployment:
      hostname: dev.canfar.espsrc.iaa.csic.es    # Change this!
      posixMapper:
        image: images.opencadc.org/platform/posix-mapper:0.3.1
        imagePullPolicy: IfNotPresent
        resourceID: ivo://espsrc.iaa.csic.es/posix-mapper
        # URI or URL of the OIDC (IAM) server.  Used to validate incoming tokens.
        oidcURI: https://ska-iam.stfc.ac.uk/

        # ID (URI) of the GMS Service.
        gmsID: ivo://skao.int/gms

        # Resources provided to the Skaha service.
        resources:
          requests:
            memory: "500M"
            cpu: "500m"
          limits:
            memory: "500M"
            cpu: "500m"

        minUID: 1000
        minGID: 900000
        registryURL: https://spsrc27.iaa.csic.es/reg

    storage:
      service:
        spec:
          persistentVolumeClaim:
            claimName: skaha-pvc # Match this label up with whatever was installed in the base install, or the desired PVC, or create dynamically provisioned storage.

    secrets:
    
    postgresql:
      auth:
        username: posixmapper
        password: posixmapperpwd
        database: mapping
        schema: mapping
      storage:
        spec:
          hostPath:
            path: "/posix-mapper/data"

    # An omission equals true, so set this explicitly.
    base:
      install: false