apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrc-traefik
  namespace: kube-system
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: espsrc-traefik
        namespace: kube-system
      #version: 34.2.0
  valuesFrom:
    - kind: ConfigMap
      name: espsrc-traefik-values