apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# use this order
resources:
  - helmrepository.yaml
  - ServiceAccount.yaml
  - ClusterRoleBinding.yaml
  - values.yaml
  - helmrelease.yaml
namespace: traefik