image: python:3.8

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - pip install sphinx sphinx-book-theme sphinxemoji

pages:
  script:
    - sphinx-build -b html docs/ public/
  artifacts:
    paths:
      - public
  only:
    - main