apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev-espsrcprometheus
  namespace: espsrcprometheus
spec:
  interval: 5m
  path: ./apps-dev/prometheus/gitops
  prune: true
  targetNamespace: espsrcprometheus
  sourceRef:
    kind: GitRepository
    name: gitrepository/espsrc-repo
  validation: client