apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev-espsrcjupyter
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps-dev/jupyterhub/gitops
  prune: true
  sourceRef:
    kind: GitRepository
    name: espsrc-repo
  validation: client