apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-espsrcjupyter
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps-dev/jupyterhub/gitops
  prune: true
  targetNamespace: espsrcjupyter
  sourceRef:
    kind: GitRepository
    name: gitrepository/espsrc-repo
  validation: client