apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: espsrc-repo
  namespace: flux-system
spec:
  url: https://gitlab.com/ska-telescope/src/deployments/espsrc
  ref:
    branch: main
  interval: 5m
  branch: main