apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-jh
  namespace: jupyterhub-test
spec:
  refreshInterval: "15s" 
  secretStoreRef:
    name: vault-secret-store 
    kind: SecretStore
  target:
    name: jupyterhub-secrets
    creationPolicy: Owner 
  data:
    - secretKey: CLIENT-ID 
      remoteRef:
        key: app/data/jupyter 
        property: client-id 
    - secretKey: CLIENT-SECRET 
      remoteRef:
        key: app/data/jupyter 
        property: client-secret 
    - secretKey: TOKEN 
      remoteRef:
        key: app/data/jupyter 
        property: token 