apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub-test
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: jupyterhub
      sourceRef:
        kind: HelmRepository
        name: jupyterhub-repository
        namespace: flux-system
      version: 3.3.8
  valuesFrom:
    - kind: Secret
      name: external-secret-jh
    #- kind: ConfigMap
    #  name: jupyterhub-values
  values: 
    proxy:
      secretToken: CLIENT-ID
      service:
        type: NodePort
        nodePorts:
          http: 31080
