apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub-test
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: jupyterhub
      sourceRef:
        kind: HelmRepository
        name: jupyterhub-repository
        namespace: flux-system
      version: 3.3.8
  valuesFrom:
    - kind: Secret
      name: jupyterhub-secrets
      valuesKey: TOKEN
      targetPath: proxy.secretToken
      optional: false
    - kind: Secret
      name: jupyterhub-secrets
      valuesKey: CLIENT-ID
      targetPath: hub.GenericOAuthenticator.client_id
      optional: false
    - kind: Secret
      name: jupyterhub-secrets
      valuesKey: CLIENT-SECRET
      targetPath: hub.GenericOAuthenticator.client_secret
      optional: false
    - kind: ConfigMap
      name: jupyterhub-values
  
