apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub-test
spec:
  chart:
    spec:
      chart: jupyterhub
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: flux-system
      version: 3.3.8
  valuesFrom:
    - configMapKeyRef:
        name: jupyterhub-values
        key: values.yaml
