apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ServiceAccount.yaml
  - SecretStore.yaml
  - ExternalSecret.yaml
  - helmrepository.yaml
  - values-prod.yaml
  - helmrelease.yaml
  
  