apiVersion: helm.sh/v1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  chart:
    repository: https://jupyterhub.github.io/helm-chart
    name: jupyterhub
    version: 
  values:

    
    
    hub:
      config:
        Authenticator:
          enable_auth_state: true
          allow_all: true
        GenericOAuthenticator:
          login_service: "SKA IAM Prototype"
          client_id: 
            valueFrom:
              secretKeyRef:
                name: jupyterhub-secret
                key: client-id
          client_secret: 
            valueFrom:
              secretKeyRef:
                name: jupyterhub-secret
                key: secret-id