apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jupyterhub-token-secret
  namespace: jupyterhub-test
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: jupyterhub-token-secret
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: service/jupyterhub
        property: client_secret
