apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: espsrcgatekeeper-s
  #namespace: espsrcgatekeeper
  namespace: gatekeeper
spec:
  refreshInterval: "15s" 
  secretStoreRef:
    name: vault-secret-store-gatekeeper
    kind: SecretStore
  target:
    name: espsrcgatekeeper-s
    creationPolicy: Owner 
  data:
    - secretKey: CLIENT-ID 
      remoteRef:
        key: app/data/espsrcgatekeeper 
        property: CLIENT-ID 
    - secretKey: CLIENT-SECRET 
      remoteRef:
        key: app/data/espsrcgatekeeper 
        property: CLIENT-SECRET 