apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: espsrcgatekeeper-chart
  namespace: espsrcgatekeeper
spec:
  chart: oci://spsrc26.iaa.csic.es/espsrc-cicd/ska-src-service-gatekeeper
  version: "0.0.3"  # Ajusta esto a la versión correcta
  interval: 5m

