apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: espsrcgatekeeper-repo
  namespace: espsrcgatekeeper
spec:
  interval: 5m
  helmCharts:
  - name: ska-src-service-gatekeeper
    repo: https://gitlab.com/api/v4/projects/61396570/packages/helm/stable
    #version: 0.0.3

  #url:  https://gitlab.com/api/v4/projects/60950975/packages/helm/stable
  #url: https://gitlab.com/api/v4/projects/61396570/packages/helm/stable
  #url: https://gitlab.com/ska-telescope/src/src-dm/ska-src-dm-da-service-gatekeeper