apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrcgatekeeper-test
  namespace: gatekeeper

spec:
  interval: 5m0s
  chart:
    spec:
      chart: ska-src-dm-da-service-gatekeeper
      version: "0.2.0"
      sourceRef:
        kind: HelmRepository
        name: espsrcgatekeeper-repo
        namespace: gatekeeper
  valuesFrom:
    - kind: Secret
      name: espsrcgatekeeper-s
      valuesKey: CLIENT-ID
      targetPath: espsrcgatekeeper.site_capabilities_gatekeeper_client_id
      optional: false
    - kind: Secret
      name: espsrcgatekeeper-s
      valuesKey: CLIENT-SECRET
      targetPath: espsrcgatekeeper.site_capabilities_gatekeeper_client_secret
      optional: false
    - kind: ConfigMap
      name: espsrcgatekeeper-values