apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: espsrcgatekeeper-repo
  namespace: flux-system
spec:
  interval: 5m
  url:  hhttps://gitlab.com/ska-telescope/src/src-dm/ska-src-dm-da-service-gatekeeper
