apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrcgatekeeper
  namespace: gatekeeper

spec:
  interval: 5m0s
  chart:
    spec:
      chart: ska-src-dm-da-service-gatekeeper
      version: "0.2.0"
      sourceRef:
        kind: HelmRepository
        name: espsrcgatekeeper-repo
        namespace: gatekeeper
  install:
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: espsrcgatekeeper-s
      valuesKey: CLIENT-ID
      targetPath: gatekeeper.siteCapabilities.clientId
      optional: false
    - kind: Secret
      name: espsrcgatekeeper-s
      valuesKey: CLIENT-SECRET
      targetPath: gatekeeper.siteCapabilities.clientSecret
      optional: false
    - kind: ConfigMap
      name: espsrcgatekeeper-values