apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: espsrcgatekeeper-ingress
  namespace: espsrcgatekeeper
  #annotations:
  #  traefik.ingress.kubernetes.io/router.middlewares: espsrcgatekeeper-strip-espsrcgatekeeper@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: "dev.gatekeeper.espsrc.iaa.csic.es"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: proxy-public
                port:
                  number: 80