apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: espsrcecho-s
  namespace: espsrcecho
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: espsrcecho-s
    creationPolicy: Owner
  data:
    - secretKey: CLIENT-ID
      remoteRef:
        key: app/data/espsrcecho
        property: client-id
    - secretKey: CLIENT-SECRET
      remoteRef:
        key: app/data/espsrcecho
        property: client-secret
    - secretKey: TOKEN
      remoteRef:
        key: app/data/espsrcecho
        property: token