apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  type: NodePort  # Cambiado de ClusterIP a NodePort
  selector:
    app: echoserver
  ports:
    - port: 80               # Puerto en el que el servicio estara disponible
      targetPort: 80         # Puerto en el que el contenedor esta escuchando
      protocol: TCP
      nodePort: 31101        # Puerto NodePort especifico que deseas
