apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: espsrcecho-ingress
  namespace: espsrcecho
  #annotations:
  #  traefik.ingress.kubernetes.io/router.middlewares: espsrcecho-strip-espsrcecho@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: "dachs-service-00.iaa.csic.es"
      http:
        paths:
          - path: "/echo"
            pathType: Prefix
            backend:
              service:
                name: proxy-public
                port:
                  number: 80