apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: jupyterhub-test
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "app/notebook"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
