apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ServiceAccount.yaml
  - ClusterRoleBinding.yaml
  - SecretStore.yaml
  - ExternalSecret.yaml
  - helmrepository.yaml
  - values.yaml
  - helmrelease.yaml
  