apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: espsrcsoda-s
  namespace: espsrcsoda
spec:
  refreshInterval: "15s" 
  secretStoreRef:
    name: vault-secret-store 
    kind: SecretStore
  target:
    name: espsrcsoda-s
    creationPolicy: Owner 
  data:
    - secretKey: CLIENT-ID 
      remoteRef:
        key: app/data/espsrcsoda 
        property: client-id 
    - secretKey: CLIENT-SECRET 
      remoteRef:
        key: app/data/espsrcsoda 
        property: client-secret 