apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrcsoda-test
  namespace: espsrcsoda
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: soda
      sourceRef:
        kind: HelmRepository
        name: espsrcsoda-repo
        namespace: flux-system
      version: 0.0.2
  valuesFrom:
    - kind: Secret
      name: espsrcsoda-s
      valuesKey: CLIENT-ID
      targetPath: 
      optional: false
    - kind: Secret
      name: espsrcsoda-s
      valuesKey: CLIENT-SECRET
      targetPath: 
      optional: false
    - kind: ConfigMap
      name: soda-values