apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrcsoda-test
  namespace: espsrcsoda
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: ska-src-soda
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: espsrcsoda-repo
        namespace: espsrcsoda
  install:
    createNamespace: true
      
  valuesFrom:
    - kind: ConfigMap
      name: soda-values