apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: espsrcsoda-repo
  namespace: espsrcsoda
spec:
  interval: 5m
  url:  https://gitlab.com/api/v4/projects/61599309/packages/helm/stable