apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: espsrcsoda-ingress
  namespace: espsrcsoda
  #annotations:
  #  traefik.ingress.kubernetes.io/router.middlewares: espsrcsoda-strip-espsrcsoda@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: "dachs-service-00.iaa.csic.es"
      http:
        paths:
          - path: "/soda"
            pathType: Prefix
            backend:
              service:
                name: proxy-public
                port:
                  number: 80