apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - ServiceAccount.yaml
  - ClusterRoleBinding.yaml
  - SecretStore.yaml
  - ExternalSecret.yaml
  - pvc.yaml
  - values.yaml
  - helmrelease.yaml
  #- pvc-patch.yaml
#patches:
  #### Patching where the data go ####
#  - target:
#      kind: Deployment
#      name: ska-src-soda
#    path: pvc-patch.yaml
