apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-access-rolebinding
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: espsrcprometheus
    namespace: espsrcprometheus
  - kind: ServiceAccount
    name: espsrcblackbox
    namespace: espsrcprometheus
  - kind: ServiceAccount
    name: espsrcgrafana
    namespace: espsrcgrafana
