---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: espsrcprometheus-s
  #namespace: espsrcgrafana
  namespace: espsrcprometheus
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store-grafana
    kind: SecretStore
  target:
    name: espsrcprometheus-s
    creationPolicy: Owner
  data:
#    - secretKey: ADMINUSER
#      remoteRef:
#        key: app/data/espsrcgrafana
#        property: adminuser
#    - secretKey: ADMINPASSWORD
#      remoteRef:
#        key: app/data/espsrcgrafana
#        property: adminpassword
    - secretKey: GRAFANA-ID
      remoteRef:
        key: app/data/espsrcprometheus
        property: grafana-id
    - secretKey: GRAFANA-SECRET
      remoteRef:
        key: app/data/espsrcprometheus
        property: grafana-secret