---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: espsrcgrafana-s
  #namespace: espsrcgrafana
  namespace: espsrcprometheus
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store-grafana
    kind: SecretStore
  target:
    name: espsrcgrafana-s
    creationPolicy: Owner
  data:
    - secretKey: ADMINUSER
      remoteRef:
        key: app/data/espsrcgrafana
        property: adminuser
    - secretKey: ADMINPASSWORD
      remoteRef:
        key: app/data/espsrcgrafana
        property: adminpassword