apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: espsrcprometheus-s
  namespace: espsrcprometheus
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store-prometheus
    kind: SecretStore
  target:
    name: espsrcprometheus-s
    creationPolicy: Owner
  data:
    - secretKey: CLIENT-ID
      remoteRef:
        key: app/data/espsrcprometheus
        property: client-id
    - secretKey: CLIENT-SECRET
      remoteRef:
        key: app/data/espsrcprometheus
        property: client-secret
  secretStoreRef:
    name: vault-secret-store-grafana
    kind: SecretStore
  target:
    name: espsrcgrafana-s
    creationPolicy: Owner
  data:
    - secretKey: CLIENT-ID
      remoteRef:
        key: app/data/espsrcgrafana
        property: client-id
    - secretKey: CLIENT-SECRET
      remoteRef:
        key: app/data/espsrcgrafana
        property: client-secret
    - secretKey: ADMINUSER
      remoteRef:
        key: app/data/espsrcgrafana
        property: adminUser
    - secretKey: ADMINPASSWORD
      remoteRef:
        key: app/data/espsrcgrafana
        property: adminPassword