apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrcgrafana-test
  namespace: espsrcprometheus
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: espsrcgrafana-helmrepo
        #namespace: flux-system
        namespace: espsrcprometheus
      #version: 3.3.8
  valuesFrom:
#    - kind: Secret
#      name: espsrcprometheus-s
#      valuesKey: TOKEN
#      targetPath: proxy.secretToken
#      optional: false
    - kind: Secret
      name: espsrcprometheus-s
      valuesKey: CLIENT-ID
      targetPath: hub.config.GenericOAuthenticator.client_id
      optional: false
    - kind: Secret
      name: espsrcprometheus-s
      valuesKey: CLIENT-SECRET
      targetPath: hub.config.GenericOAuthenticator.client_secret
      optional: false
    - kind: ConfigMap
      name: grafana-values