apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: espsrcgrafana-helmrepo
  #namespace: espsrcgrafana
  namespace: espsrcprometheus
spec:
  interval: 5m
  url:  https://grafana.github.io/helm-charts