apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: espsrcprometheus-helmrepo
  namespace: espsrcprometheus
spec:
  interval: 5m
  url:  https://prometheus-community.github.io/helm-charts