apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrcprometheus-test
  namespace: espsrcprometheus
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: espsrcprometheus-helmrepo
        namespace: espsrcprometheus
      version: 27.3.0
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-values
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrcblackbox-test
  namespace: espsrcprometheus
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: espsrcprometheus-helmrepo
        namespace: espsrcprometheus
      version: 9.2.0
  valuesFrom:
    - kind: ConfigMap
      name: blackbox-values
  