apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: espsrcprometheus-helmrepo
  namespace: espsrcgrafana
spec:
  interval: 5m
  url:  https://grafana.github.io/helm-charts