apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: espsrcgrafana-test
  #namespace: espsrcgrafana
  namespace: espsrcprometheus
spec:
  interval: 5m0s  # Intervalo para verificar actualizaciones
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: espsrcgrafana-helmrepo
        #namespace: espsrcgrafana
        namespace: espsrcprometheus
      version: 8.9.0
  valuesFrom:
    - kind: Secret
      name: espsrcprometheus-s
      valuesKey: grafana-id
      targetPath: adminUser
      optional: false
    - kind: Secret
      name: espsrcprometheus-s
      valuesKey: GRAFANA-SECRET
      targetPath: adminPassword
      optional: false
    - kind: ConfigMap
      name: grafana-values