apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: prometheus-secret-store
  namespace: espsrcprometheus
spec:
  provider:
   vault:
     server: "http://vault.vault.svc.cluster.local:8200"
     path: "app"
     version: "v2"
     auth:
       kubernetes:
         mountPath: "kubernetes"
         role: "espsrcprometheus"
         serviceAccountRef:
           name: "espsrcprometheus"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: grafana-secret-store
  namespace: espsrcprometheus
spec:
  provider:
   vault:
     server: "http://vault.vault.svc.cluster.local:8200"
     path: "app"
     version: "v2"
     auth:
       kubernetes:
         mountPath: "kubernetes"
         role: "espsrcgrafana"
         serviceAccountRef:
           name: "espsrcgrafana"