apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-values
  namespace: espsrcprometheus
data:
  values.yaml: |
    global:
      scrape_interval: 300s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              - https://notebook.espsrc.iaa.csic.es/
            labels:
              name: 'Notebook'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-values
  namespace: espsrcprometheus
data:
  values.yaml: |
    server: 
      root_url: https://dev.monitor.espsrc.iaa.csic.es
      #server_from_sub_path: true
    auth:
      generic_oauth:
        enabled: true
        name: OAuth
        allow_sign_up: true
        client_id: 2cdc0aa5-77c7-4045-9b81-9f1493555645
        client_secret: YOUR_CLIENT_SECRET
        scopes: openid email profile
        email_attribute_path: email
        login_attribute_path: preferred_username
        api_url: https://ska-iam.stfc.ac.uk/userinfo
        auth_url: https://ska-iam.stfc.ac.uk/authorize
        token_url: https://ska-iam.stfc.ac.uk/token
        auto_login: false
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://10.109.24.12
            #access: proxy
            isDefault: true

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        kubernetes-apiserver:
          gnetId: 15661
           revision: 2
           datasource: 
            type: prometheus
            #uid: "victoriametrics-prod-all"
          jsonData:
            refresh: 10s
            templating: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-values
  namespace: espsrcprometheus
data:
  values.yaml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          method: GET
          fail_if_ssl: false
          fail_if_not_ssl: false
          valid_status_codes: []
          follow_redirects: true
          preferred_ip_protocol: "ip4"
