apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-gatekeeper
  namespace: gatekeeper-test
spec:
  refreshInterval: "15s" 
  secretStoreRef:
    name: vault-secret-store 
    kind: SecretStore
  target:
    name: gatekeeper-secrets
    creationPolicy: Owner 
  data:
    - secretKey: CLIENT-ID 
      remoteRef:
        key: app/data/gatekeeper 
        property: client-id 
    - secretKey: CLIENT-SECRET 
      remoteRef:
        key: app/data/gatekeeper 
        property: client-secret 