apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gatekeepr-repository
  namespace: flux-system
spec:
  interval: 5m
  url:  https://ska-src-gatekeeper-repo https://gitlab.com/api/v4/projects/60950975/packages/helm/stable