apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: gatekeeper-test
spec:
  provider:
   vault:
     server: "http://vault.vault.svc.cluster.local:8200"
     path: "app" 
     version: "v2"
     auth:
       kubernetes:
         mountPath: "kubernetes"
         role: "gatekeeper" 
         serviceAccountRef:
           name: "gatekeeper"